### ISSUE TITLE
eris pkgs do --file flag not working

### ISSUE THREAD

**Issue by j-h-scheufen** [eris-ltd/eris-pm#120]
When trying to invoke the the `epm pkgs do` command with a custom file name other than epm.yaml by using the `-f | --file` flag, the file is not recognized:
```
$> eris pkgs do -c myChain -a 68112F9380F75A13F6CE2D5923F1DB8386EF1339 -f MyTest.yaml 
Performing action. This can sometimes take a wee while
Sorry, the marmots were unable to load the eris-pm jobs file. Please check your path.
ERROR =>			Unsupported Config Type ""
```
This is reproducible by simply renaming the epm.yaml to something else and using that name as the flag parameter.
The problem was experienced with both the `-f` as well as `--file` flag versions and by trying to prefix the path with the directory: `-f ./MyTest.yaml`

- [x] `docker version`: 1.10.3
- [x] `eris version`: 0.11.4
- [x] `go version`: go1.6.2 darwin/amd64
- [x] `docker-machine version`: 0.6.0, build e27fb87
- [x] operating system: OSX

**Comment by zramsay** [comment]
related to https://github.com/eris-ltd/eris-cli/issues/672
does it work if the filename is `epm.yaml` ?

**Comment by j-h-scheufen** [comment]
Yes. `--file epm.yaml` works

**Comment by benjaminbollen** [comment]
I also experienced that `--file` from a different directory did not work; but I have not reproduced this bug, so it is just a note, not a bugreport.

**Comment by pietv** [comment]
The Eris CLI `epm-config-path` contains a fix for this issue.

It should be possible now to specify an alternative file in the same directory:
```
eris pkgs do --chain simplechain --address ... --file test.yaml
eris pkgs do --chain simplechain --address ... --file ./test.yaml
```
As well as the path from the outside the package:
```
eris pkgs do --chain simplechain --address ... --file /Users/peter/test.yaml
eris pkgs do --chain simplechain --address ... --file /Users/peter/epm.yaml
```

Please test when you can. Thanks.

**Comment by zramsay** [comment]
:+1: works for me. But I did note that the `epm.json` ends up in the same directory as the filepath specified. Not sure if that is desired behaviour though I did expect it to land in `pwd`.

**Comment by zramsay** [comment]
to clarify: the `abi` directory *did* end up in `pwd`, hence why i expected the epm.json there too

**Comment by pietv** [comment]
Cool! Thanks for checking it. Yeah, good spot, I managed to reproduce it as well, but as for whether this is a bug or not, I have no idea. @compleatang or @VoR0220 can probably explain the intention behind this.

The thing is there is a piece of code that explicitly moves the `epm.json` file on the CLI side, and not touches the `abi`:

https://github.com/eris-ltd/eris-cli/blob/master/pkgs/operate.go#L536
```
		dirToMoveTo := filepath.Dir(file)
		epmFiles, err := filepath.Glob(filepath.Join(do.Path, "epm*"))
		if err != nil {
			return err
		}
```
The Glob picks up `epm` and not `abi`.

**Comment by pietv** [comment]
These are definitely bugs since `Rename` won't move files to a different filesystem:
https://github.com/eris-ltd/eris-cli/blob/master/pkgs/operate.go#L556

And it won't work for directories:
https://github.com/eris-ltd/eris-cli/blob/master/pkgs/operate.go#L556

**Comment by pietv** [comment]
This ticket might be related: https://github.com/eris-ltd/eris-cli/issues/706

**Comment by zramsay** [comment]
definitely related

**Comment by pietv** [comment]
@compleatang this is blocking on your insight why `epm.json` is moving out of the package dir and not `abi`. A bug or intended behavior?

**Comment by compleatang** [comment]
yes. that is intended behaviour. wherever the `epm.yaml` or `--file` is then the `epm.json` should go there.

**Comment by pietv** [comment]
thank you! does this mean also that `abi` should go as well? or should it stay?

**Comment by compleatang** [comment]
abi is isn't own flag by default it should be `pkgDir/abi` but i the abi flag exists it should be overridden. This is mostly in pkg.

**Comment by pietv** [comment]
indeed, there's an `--abi-path` for that. makes sense, thanks.

**Comment by pietv** [comment]
tried specifying alternative paths for both `--file` and `--abi-path` - it didn't work for me. every time it just crashes my docker host (DigitalOcean). will investigate and fix

**Comment by pietv** [comment]
Fixed in 0.12.0-rc1

**Comment by kootenpv** [comment]
Passing `--file ./other_than_epm.yaml` still does not work for me at `Eris CLI Version: 0.12.0`.

I get a `ERROR =>			Unsupported Config Type ""`
